package principal;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ivi
 */
public class NuevoInstrumento extends javax.swing.JDialog {

    int x,y;
    ConexionBD miConexion=new ConexionBD();
    Connection con=miConexion.getConexion();
    /**
     * Creates new form NuevoInstrumento
     */
    public NuevoInstrumento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            Statement misentencia=Principal.miConexion.createStatement();
            ResultSet rs=misentencia.executeQuery("SELECT * FROM musico");
            Combo musicoDef=new Combo(0,"Seleccione una opción","...");
            cmbxMusicosIN.addItem(musicoDef);
            while(rs.next()){
                Combo musico=new Combo(rs.getInt("idmusico"),rs.getString("nombre"),rs.getString("apellidos"));
                cmbxMusicosIN.addItem(musico);
            }
        } catch (SQLException ex) {
            System.out.println("ERROR Statement");  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTItuloI = new javax.swing.JPanel();
        labelTituloI = new javax.swing.JLabel();
        btnCerrarIN = new javax.swing.JButton();
        panelContenidoI = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreIN = new javax.swing.JTextField();
        txtDescripcionIN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbxMusicosIN = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        panelPieI = new javax.swing.JPanel();
        btnAnadirI = new javax.swing.JButton();
        btnLimpiarI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(419, 469));
        setUndecorated(true);

        panelTItuloI.setBackground(new java.awt.Color(188, 188, 188));
        panelTItuloI.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        labelTituloI.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        labelTituloI.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloI.setText("Añadir Instrumento");
        labelTituloI.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        labelTituloI.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                labelTituloIMouseDragged(evt);
            }
        });
        labelTituloI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelTituloIMousePressed(evt);
            }
        });

        btnCerrarIN.setBackground(new java.awt.Color(21, 101, 193));
        btnCerrarIN.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnCerrarIN.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-cerrar.png"))); // NOI18N
        btnCerrarIN.setToolTipText("Cerrar");
        btnCerrarIN.setBorder(null);
        btnCerrarIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarINActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTItuloILayout = new javax.swing.GroupLayout(panelTItuloI);
        panelTItuloI.setLayout(panelTItuloILayout);
        panelTItuloILayout.setHorizontalGroup(
            panelTItuloILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTItuloILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloI, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarIN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTItuloILayout.setVerticalGroup(
            panelTItuloILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTItuloILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTItuloILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarIN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTituloI, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContenidoI.setBackground(new java.awt.Color(0, 153, 204));
        panelContenidoI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        panelContenidoI.setPreferredSize(new java.awt.Dimension(419, 310));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setText("NOMBRE");

        txtNombreIN.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreIN.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        txtNombreIN.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreIN.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        txtNombreIN.setSelectionColor(new java.awt.Color(0, 153, 204));

        txtDescripcionIN.setBackground(new java.awt.Color(204, 204, 204));
        txtDescripcionIN.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        txtDescripcionIN.setForeground(new java.awt.Color(51, 51, 51));
        txtDescripcionIN.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        txtDescripcionIN.setSelectionColor(new java.awt.Color(0, 153, 204));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(188, 188, 188));
        jLabel3.setText("DESCRIPCIÓN");

        cmbxMusicosIN.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(188, 188, 188));
        jLabel4.setText("MÚSICO");

        txtResultado.setBackground(new java.awt.Color(0, 153, 204));
        txtResultado.setFont(new java.awt.Font("Eras Medium ITC", 1, 22)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(232, 131, 0));
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultado.setBorder(null);

        javax.swing.GroupLayout panelContenidoILayout = new javax.swing.GroupLayout(panelContenidoI);
        panelContenidoI.setLayout(panelContenidoILayout);
        panelContenidoILayout.setHorizontalGroup(
            panelContenidoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContenidoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResultado)
                    .addGroup(panelContenidoILayout.createSequentialGroup()
                        .addGroup(panelContenidoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelContenidoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNombreIN)
                            .addComponent(txtDescripcionIN)
                            .addComponent(cmbxMusicosIN, 0, 214, Short.MAX_VALUE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelContenidoILayout.setVerticalGroup(
            panelContenidoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoILayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelContenidoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panelContenidoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcionIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelContenidoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbxMusicosIN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelPieI.setBackground(new java.awt.Color(188, 188, 188));
        panelPieI.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(102, 102, 102)));
        panelPieI.setPreferredSize(new java.awt.Dimension(310, 66));

        btnAnadirI.setBackground(new java.awt.Color(21, 101, 193));
        btnAnadirI.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadirI.setText("AÑADIR");
        btnAnadirI.setBorder(null);
        btnAnadirI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirIActionPerformed(evt);
            }
        });

        btnLimpiarI.setBackground(new java.awt.Color(21, 101, 193));
        btnLimpiarI.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarI.setText("LIMPIAR");
        btnLimpiarI.setBorder(null);
        btnLimpiarI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPieILayout = new javax.swing.GroupLayout(panelPieI);
        panelPieI.setLayout(panelPieILayout);
        panelPieILayout.setHorizontalGroup(
            panelPieILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPieILayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnAnadirI, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarI, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        panelPieILayout.setVerticalGroup(
            panelPieILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPieILayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPieILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarI, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnadirI, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidoI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTItuloI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPieI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTItuloI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelContenidoI, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panelPieI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarINActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarINActionPerformed

    private void btnAnadirIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirIActionPerformed
        if(cmbxMusicosIN.getItemCount()==1){
            JOptionPane.showMessageDialog(this, "¡¡ No hay músicos creados todavia !!\nDebes crear primero un Músico para\nasignarle el instrumento", "información", JOptionPane.INFORMATION_MESSAGE);
        }else{
            txtNombreIN.requestFocus();
            String nombre=txtNombreIN.getText();
            String desc=txtDescripcionIN.getText();
            String musico=cmbxMusicosIN.getSelectedItem().toString();
            int idmusico=cmbxMusicosIN.getItemAt(cmbxMusicosIN.getSelectedIndex()).getId();

            String consulta="INSERT INTO instrumento (nombre,descripcion,idmusico) VALUES (?,?,?)";
            String consulta1="SELECT * FROM instrumento";
            boolean r1=Utilidades.ComprobarString(nombre);
            boolean r2=Utilidades.ComprobarString(desc);
            boolean r3=false;
            if(idmusico>0){
                r3=true;
            }
            if ((r1==true)&&(r2==true)&&(r3==true)){
                Instrumento i=new Instrumento();
                i.aniadirInstrumento(nombre, desc, idmusico, consulta);
                
                ConexionBD conexion=new ConexionBD();
                conexion.resultadoEnTabla(consulta1);
                txtNombreIN.setText("");
                txtDescripcionIN.setText("");
                cmbxMusicosIN.setSelectedIndex(0);
                txtResultado.setText("");
                txtNombreIN.requestFocus();
            }else if(r1==false){
                txtResultado.setText("Ingresa un nombre");
            }else if(r2==false){
                txtResultado.setText("Ingresa una descripción");
            }else if(r3==false){
                txtResultado.setText("Selecciona un Músico");
            }
        }
    }//GEN-LAST:event_btnAnadirIActionPerformed

    private void btnLimpiarIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarIActionPerformed
        txtNombreIN.setText("");
        txtDescripcionIN.setText("");
        cmbxMusicosIN.setSelectedIndex(0);
        txtNombreIN.requestFocus();
        txtResultado.setText("");
    }//GEN-LAST:event_btnLimpiarIActionPerformed

    int xx,xy;
    private void labelTituloIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTituloIMousePressed
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_labelTituloIMousePressed

    private void labelTituloIMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTituloIMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_labelTituloIMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoInstrumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoInstrumento dialog = new NuevoInstrumento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirI;
    private javax.swing.JButton btnCerrarIN;
    private javax.swing.JButton btnLimpiarI;
    private javax.swing.JComboBox<Combo> cmbxMusicosIN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelTituloI;
    private javax.swing.JPanel panelContenidoI;
    private javax.swing.JPanel panelPieI;
    private javax.swing.JPanel panelTItuloI;
    private javax.swing.JTextField txtDescripcionIN;
    private javax.swing.JTextField txtNombreIN;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
