package principal;

/**
 *
 * @author dawa04
 */
public class NuevoMusico extends javax.swing.JDialog {

    /*declaro estas variables para la posicion de la ventana.Y con los eventos  mousepressed y mousedragged consigo el efecto 
    para agarrar y mover la ventana*/
    int x,y;
    /**
     * Creates new form NuevoMusico
     */
    public NuevoMusico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        txtNombreMN.requestFocus();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        btnCerrarMN = new javax.swing.JButton();
        panelContenidoM = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtApellidosMN = new javax.swing.JTextField();
        txtNombreMN = new javax.swing.JTextField();
        txtDireccionMN = new javax.swing.JTextField();
        dtFechaMN = new com.toedter.calendar.JDateChooser();
        txtResultado = new javax.swing.JTextField();
        panelPieM = new javax.swing.JPanel();
        btnAnadirM = new javax.swing.JButton();
        btnLimpiarM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(188, 188, 188));
        setUndecorated(true);

        panelTitulo.setBackground(new java.awt.Color(188, 188, 188));
        panelTitulo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        panelTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelTitulo.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Añadir Músico");
        labelTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        labelTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                labelTituloMouseDragged(evt);
            }
        });
        labelTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelTituloMousePressed(evt);
            }
        });

        btnCerrarMN.setBackground(new java.awt.Color(21, 101, 193));
        btnCerrarMN.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnCerrarMN.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarMN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-cerrar.png"))); // NOI18N
        btnCerrarMN.setToolTipText("Cerrar");
        btnCerrarMN.setAlignmentY(0.0F);
        btnCerrarMN.setBorder(null);
        btnCerrarMN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarMNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(btnCerrarMN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTituloLayout.createSequentialGroup()
                        .addComponent(btnCerrarMN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelContenidoM.setBackground(new java.awt.Color(0, 153, 204));
        panelContenidoM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(188, 188, 188));
        jLabel3.setText("APELLIDOS");

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(188, 188, 188));
        jLabel4.setText("DIRECCIÓN");

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(188, 188, 188));
        jLabel5.setText("F. NACIMIENTO");

        txtApellidosMN.setBackground(new java.awt.Color(204, 204, 204));
        txtApellidosMN.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        txtApellidosMN.setForeground(new java.awt.Color(51, 51, 51));
        txtApellidosMN.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        txtApellidosMN.setSelectionColor(new java.awt.Color(0, 153, 204));

        txtNombreMN.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreMN.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        txtNombreMN.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreMN.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        txtNombreMN.setSelectionColor(new java.awt.Color(0, 153, 204));

        txtDireccionMN.setBackground(new java.awt.Color(204, 204, 204));
        txtDireccionMN.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        txtDireccionMN.setForeground(new java.awt.Color(51, 51, 51));
        txtDireccionMN.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        txtDireccionMN.setSelectionColor(new java.awt.Color(0, 153, 204));

        dtFechaMN.setBackground(new java.awt.Color(204, 204, 204));
        dtFechaMN.setForeground(new java.awt.Color(51, 51, 51));

        txtResultado.setBackground(new java.awt.Color(0, 153, 204));
        txtResultado.setFont(new java.awt.Font("Eras Medium ITC", 1, 22)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(232, 131, 0));
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultado.setBorder(null);

        javax.swing.GroupLayout panelContenidoMLayout = new javax.swing.GroupLayout(panelContenidoM);
        panelContenidoM.setLayout(panelContenidoMLayout);
        panelContenidoMLayout.setHorizontalGroup(
            panelContenidoMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContenidoMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResultado)
                    .addGroup(panelContenidoMLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dtFechaMN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelContenidoMLayout.createSequentialGroup()
                        .addGroup(panelContenidoMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelContenidoMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidosMN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreMN, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtDireccionMN))))
                .addContainerGap())
        );
        panelContenidoMLayout.setVerticalGroup(
            panelContenidoMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoMLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelContenidoMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelContenidoMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidosMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelContenidoMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelContenidoMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtFechaMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelPieM.setBackground(new java.awt.Color(188, 188, 188));
        panelPieM.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(102, 102, 102)));

        btnAnadirM.setBackground(new java.awt.Color(21, 101, 193));
        btnAnadirM.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadirM.setText("AÑADIR");
        btnAnadirM.setBorder(null);
        btnAnadirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirMActionPerformed(evt);
            }
        });

        btnLimpiarM.setBackground(new java.awt.Color(21, 101, 193));
        btnLimpiarM.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarM.setText("LIMPIAR");
        btnLimpiarM.setBorder(null);
        btnLimpiarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPieMLayout = new javax.swing.GroupLayout(panelPieM);
        panelPieM.setLayout(panelPieMLayout);
        panelPieMLayout.setHorizontalGroup(
            panelPieMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPieMLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnAnadirM, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarM, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        panelPieMLayout.setVerticalGroup(
            panelPieMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPieMLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPieMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarM, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnadirM, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidoM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPieM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelContenidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelPieM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarMNActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarMNActionPerformed

    private void btnAnadirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirMActionPerformed
        String consulta="SELECT * FROM musico";
        String consulta1="INSERT INTO musico (nombre,apellidos,direccion,fecha_nac) VALUES (?,?,?,?)";
        String nombre=txtNombreMN.getText();
        String ape=txtApellidosMN.getText();
        String dire=txtDireccionMN.getText();

        boolean r1=Utilidades.ComprobarString(txtNombreMN.getText());
        boolean r2=Utilidades.ComprobarString(txtApellidosMN.getText());
        boolean r3=Utilidades.ComprobarString(txtDireccionMN.getText());
        boolean r4=false;
        if(dtFechaMN.getDate()!=null){
            r4=true;
        }

        if ((r1==true)&&(r2==true)&&(r3==true)&&(r4==true)){
             java.util.Date ud = dtFechaMN.getDate();
            long d = ud.getTime();
            java.sql.Date fecha = new java.sql.Date(d);
            Musico m=new Musico();
            m.aniadirMusico(nombre, ape, dire, fecha, consulta1);
            
            ConexionBD conexion=new ConexionBD();
            conexion.resultadoEnTabla(consulta);
            
            txtResultado.setText("");
            txtNombreMN.setText("");
            txtApellidosMN.setText("");
            txtDireccionMN.setText("");
            dtFechaMN.setDate(null);
        }else if(r1==false){
            txtResultado.setText("Ingresa el nombre del músico");
            txtNombreMN.requestFocus();
        }else if(r2==false){
            txtResultado.setText("Ingresa apellidos del músico");
            txtApellidosMN.requestFocus();
        }else if(r3==false){
            txtResultado.setText("Ingresa una direccion");
            txtDireccionMN.requestFocus();
        }else if(r4==false){
            txtResultado.setText("Ingresa una fecha");
        }
    }//GEN-LAST:event_btnAnadirMActionPerformed

    private void btnLimpiarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMActionPerformed
        txtNombreMN.setText("");
        txtApellidosMN.setText("");
        txtDireccionMN.setText("");
        txtResultado.setText("");
        dtFechaMN.setDate(null);
        txtNombreMN.requestFocus();
    }//GEN-LAST:event_btnLimpiarMActionPerformed

    int xx,xy;
    private void labelTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTituloMousePressed
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_labelTituloMousePressed

    private void labelTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTituloMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_labelTituloMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoMusico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoMusico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoMusico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoMusico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoMusico dialog = new NuevoMusico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirM;
    private javax.swing.JButton btnCerrarMN;
    private javax.swing.JButton btnLimpiarM;
    private com.toedter.calendar.JDateChooser dtFechaMN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelContenidoM;
    private javax.swing.JPanel panelPieM;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTextField txtApellidosMN;
    private javax.swing.JTextField txtDireccionMN;
    private javax.swing.JTextField txtNombreMN;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
