package principal;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import recursos.MyIcon;

/**
 *
 * @author IvI
 */
public class Principal extends javax.swing.JFrame {

    public static DefaultTableModel modelo;
    public static Connection miConexion;
    int x,y;
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        ConexionBD conexion=new ConexionBD("192.168.0.177","ivan","Abcd1234!","crudBanda");
        miConexion=conexion.getConexion();
 
        //  Consulta para mostrar las cabeceras con texto personalizado
        String consulta="SELECT idmusico AS Músico, nombre AS Nombre, apellidos AS Apellidos, direccion AS Dirección, fecha_nac AS 'Fecha de Nacimiento' FROM musico";
        //   Al crear el modelo sobreescribo el método iscell editable para que solo se pueda editar desde el boton modificar 
        modelo=new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        conexion.resultadoEnTabla(consulta);
        tablaMusicos.setModel(modelo);
        //  Al pulsar en la cabecerar ordena ascendente o descendente
        tablaMusicos.setAutoCreateRowSorter(true);
        
        tablaInstrumentos.setModel(modelo);
        tablaInstrumentos.setAutoCreateRowSorter(true);
        
        txtModNombre.setVisible(false);
        txtModApellidos.setVisible(false);
        txtModDireccion.setVisible(false);
        jdcCal.setVisible(false);
        lNombreM.setVisible(false);
        lApellidosM.setVisible(false);
        lDireccionM.setVisible(false);
        lFechaM.setVisible(false);
        
        txtModNombreI.setVisible(false);
        txtModDescripcionI.setVisible(false);
        cmbxModI.setVisible(false);
        lNombreI.setVisible(false);
        lDescripcionI.setVisible(false);
        lMusicoI.setVisible(false);
    }
    
    @Override
        public Image getIconImage(){
        Image imaxe = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/logoApp.png"));
        return imaxe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelCabecera = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtBuscador = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnMinim = new javax.swing.JButton();
        labelLogo = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        panelPestanas = new javax.swing.JTabbedPane();
        panelMusicos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMusicos = new javax.swing.JTable();
        panelInstrumentos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaInstrumentos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtModNombreI = new javax.swing.JTextField();
        txtModDescripcionI = new javax.swing.JTextField();
        cmbxModI = new javax.swing.JComboBox<>();
        lNombreM = new javax.swing.JLabel();
        lApellidosM = new javax.swing.JLabel();
        lDireccionM = new javax.swing.JLabel();
        lFechaM = new javax.swing.JLabel();
        txtModNombre = new javax.swing.JTextField();
        txtModApellidos = new javax.swing.JTextField();
        txtModDireccion = new javax.swing.JTextField();
        jdcCal = new com.toedter.calendar.JDateChooser();
        lNombreI = new javax.swing.JLabel();
        lDescripcionI = new javax.swing.JLabel();
        lMusicoI = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(188, 188, 188));
        setIconImage(getIconImage());
        setUndecorated(true);

        panelCabecera.setBackground(new java.awt.Color(0, 153, 204));
        panelCabecera.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(188, 188, 188)));
        panelCabecera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnNuevo.setBackground(new java.awt.Color(21, 101, 193));
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("NUEVO");
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.setBorder(null);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(21, 101, 193));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setMaximumSize(new java.awt.Dimension(48, 15));
        btnEliminar.setMinimumSize(new java.awt.Dimension(48, 15));
        btnEliminar.setPreferredSize(new java.awt.Dimension(48, 15));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(21, 101, 193));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("MODIFICAR");
        btnModificar.setToolTipText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.setBorderPainted(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(21, 101, 193));
        btnCerrar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-cerrar.png"))); // NOI18N
        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setMaximumSize(new java.awt.Dimension(40, 40));
        btnCerrar.setMinimumSize(new java.awt.Dimension(40, 40));
        btnCerrar.setPreferredSize(new java.awt.Dimension(40, 40));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("CRUD Músicos e Instrumentos");
        labelTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscador.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        txtBuscador.setForeground(new java.awt.Color(51, 51, 51));
        txtBuscador.setText("Buscar...");
        txtBuscador.setToolTipText("Buscar...");
        txtBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscadorMouseClicked(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscador)
                .addContainerGap())
        );

        btnMinim.setBackground(new java.awt.Color(21, 101, 193));
        btnMinim.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMinim.setForeground(new java.awt.Color(255, 255, 255));
        btnMinim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-minimizar.png"))); // NOI18N
        btnMinim.setToolTipText("Minimizar");
        btnMinim.setBorder(null);
        btnMinim.setBorderPainted(false);
        btnMinim.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMinim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinim.setMaximumSize(new java.awt.Dimension(40, 40));
        btnMinim.setMinimumSize(new java.awt.Dimension(40, 40));
        btnMinim.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMinim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimActionPerformed(evt);
            }
        });

        labelLogo.setBackground(new java.awt.Color(187, 187, 187));
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        labelLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        labelLogo.setOpaque(true);
        labelLogo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                labelLogoMouseDragged(evt);
            }
        });
        labelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelLogoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinim, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMinim, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPrincipal.setBackground(new java.awt.Color(188, 188, 188));

        panelPestanas.setBackground(new java.awt.Color(188, 188, 188));
        panelPestanas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelPestanas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPestanasMouseClicked(evt);
            }
        });

        panelMusicos.setBackground(new java.awt.Color(188, 188, 188));

        jScrollPane1.setBackground(new java.awt.Color(188, 188, 188));

        tablaMusicos.setBackground(new java.awt.Color(188, 188, 188));
        tablaMusicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Músico", "Nombre", "Apellidos", "Dirección", "Fecha de Nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMusicos.setSelectionBackground(new java.awt.Color(0, 153, 204));
        tablaMusicos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaMusicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMusicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMusicos);

        javax.swing.GroupLayout panelMusicosLayout = new javax.swing.GroupLayout(panelMusicos);
        panelMusicos.setLayout(panelMusicosLayout);
        panelMusicosLayout.setHorizontalGroup(
            panelMusicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMusicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMusicosLayout.setVerticalGroup(
            panelMusicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMusicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelPestanas.addTab("Musicos", panelMusicos);

        panelInstrumentos.setBackground(new java.awt.Color(188, 188, 188));

        jScrollPane4.setBackground(new java.awt.Color(188, 188, 188));

        tablaInstrumentos.setBackground(new java.awt.Color(188, 188, 188));
        tablaInstrumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaInstrumentos.setSelectionBackground(new java.awt.Color(0, 153, 204));
        tablaInstrumentos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaInstrumentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaInstrumentosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaInstrumentos);

        javax.swing.GroupLayout panelInstrumentosLayout = new javax.swing.GroupLayout(panelInstrumentos);
        panelInstrumentos.setLayout(panelInstrumentosLayout);
        panelInstrumentosLayout.setHorizontalGroup(
            panelInstrumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstrumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelInstrumentosLayout.setVerticalGroup(
            panelInstrumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstrumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelPestanas.addTab("Instrumentos", panelInstrumentos);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPestanas)
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPestanas, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(188, 188, 188));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 2, 2, new java.awt.Color(188, 188, 188)));
        jPanel3.setMaximumSize(new java.awt.Dimension(896, 64));
        jPanel3.setMinimumSize(new java.awt.Dimension(896, 64));
        jPanel3.setPreferredSize(new java.awt.Dimension(896, 64));

        lNombreM.setForeground(new java.awt.Color(60, 63, 65));
        lNombreM.setText("Nombre");

        lApellidosM.setForeground(new java.awt.Color(60, 63, 65));
        lApellidosM.setText("Apellidos");

        lDireccionM.setForeground(new java.awt.Color(60, 63, 65));
        lDireccionM.setText("Dirección");

        lFechaM.setForeground(new java.awt.Color(60, 63, 65));
        lFechaM.setText("Fecha de Nacimiento");

        lNombreI.setForeground(new java.awt.Color(60, 63, 65));
        lNombreI.setText("Nombre");

        lDescripcionI.setForeground(new java.awt.Color(60, 63, 65));
        lDescripcionI.setText("Descripción");

        lMusicoI.setForeground(new java.awt.Color(60, 63, 65));
        lMusicoI.setText("Músico");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNombreM))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lApellidosM))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lDireccionM))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lFechaM)
                            .addComponent(jdcCal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModNombreI, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNombreI))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModDescripcionI, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lDescripcionI))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lMusicoI)
                            .addComponent(cmbxModI, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombreM)
                    .addComponent(lApellidosM)
                    .addComponent(lDireccionM)
                    .addComponent(lFechaM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcCal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtModApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtModDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNombreI)
                    .addComponent(lDescripcionI)
                    .addComponent(lMusicoI, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cmbxModI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtModNombreI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtModDescripcionI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        txtBuscador.setText("Buscar...");
        txtModNombre.setVisible(false);
        txtModApellidos.setVisible(false);
        txtModDireccion.setVisible(false);
        jdcCal.setVisible(false);
        lNombreM.setVisible(false);
        lApellidosM.setVisible(false);
        lDireccionM.setVisible(false);
        lFechaM.setVisible(false);
        
        txtModNombreI.setVisible(false);
        txtModDescripcionI.setVisible(false);
        cmbxModI.setVisible(false);
        lNombreI.setVisible(false);
        lDescripcionI.setVisible(false);
        lMusicoI.setVisible(false);

        int indice = panelPestanas.getSelectedIndex();
        if(indice==0){
             tablaMusicos.clearSelection();
             NuevoMusico musico= new NuevoMusico(this, true);
             musico.setVisible(true);
        }else{
            tablaInstrumentos.clearSelection();
            NuevoInstrumento inst= new NuevoInstrumento(this, true);
            inst.setVisible(true);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String consulta="SELECT * FROM musico";
        String consulta2="SELECT * FROM instrumento";

        int indicePestana = panelPestanas.getSelectedIndex();
        if(indicePestana==0){//pestaña 0 tabla musicos
            txtBuscador.setText("Buscar...");
            txtModNombre.setVisible(false);
            txtModApellidos.setVisible(false);
            txtModDireccion.setVisible(false);
            jdcCal.setVisible(false);
            lNombreM.setVisible(false);
            lApellidosM.setVisible(false);
            lDireccionM.setVisible(false);
            lFechaM.setVisible(false);
            int indice=tablaMusicos.getSelectedRow();
            if(indice<0){
                JOptionPane.showMessageDialog(this, "Selecciona el registro a borrar", "información", JOptionPane.INFORMATION_MESSAGE);
            }else{
                int id=(int)tablaMusicos.getValueAt(indice, 0);
                MyIcon icono = new MyIcon();
                icono.setRuta("/img/trash2.png");
                int resp = JOptionPane.showConfirmDialog(this, "¿Esta seguro de Eliminar?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE,icono);
                if(resp==0){
                    
                    String consulta1="DELETE FROM musico WHERE idmusico='"+id+"'";
                    Utilidades.eliminar(id, consulta1);
                    ConexionBD conexion=new ConexionBD();
                    conexion.resultadoEnTabla(consulta);
                    tablaMusicos.clearSelection();
                } else{
                    tablaMusicos.clearSelection();
                } 
            }
        }else{//pestaña=1 tabla instrumentos
            txtBuscador.setText("Buscar...");
            txtModNombreI.setVisible(false);
            txtModDescripcionI.setVisible(false);
            cmbxModI.setVisible(false);
            lNombreI.setVisible(false);
            lDescripcionI.setVisible(false);
            lMusicoI.setVisible(false);
            int indice=tablaInstrumentos.getSelectedRow();
            if(indice<0){
                JOptionPane.showMessageDialog(this, "Selecciona el registro a borrar", "información", JOptionPane.INFORMATION_MESSAGE);
            }else{
                int id=(int)tablaInstrumentos.getValueAt(indice, 0);
                MyIcon icono = new MyIcon();
                icono.setRuta("/img/trash2.png");
                int resp = JOptionPane.showConfirmDialog(this, "¿Esta seguro de Eliminar?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE,icono);
                if(resp==0){
                    String consulta1="DELETE FROM instrumento WHERE idinstrumento='"+id+"'";
                    Utilidades.eliminar(id,consulta1);
                    
                    ConexionBD conexion=new ConexionBD();
                    conexion.resultadoEnTabla(consulta2);
                    tablaInstrumentos.clearSelection();
                } else{
                    tablaInstrumentos.clearSelection();
                } 
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Musico m=new Musico();
        Instrumento i=new Instrumento();
        txtBuscador.setText("Buscar...");
        int indicePestana = panelPestanas.getSelectedIndex();
        if(indicePestana==0){//pestaña 0 tabla musico
            int indice=tablaMusicos.getSelectedRow();
            if(indice<0){
                JOptionPane.showMessageDialog(this, "Selecciona el registro a modificar", "información", JOptionPane.INFORMATION_MESSAGE);
            }else{
                int id=(int) tablaMusicos.getValueAt(indice, 0);
                String nombre=txtModNombre.getText();
                String ape=txtModApellidos.getText();
                String dire=txtModDireccion.getText();

                boolean r1=Utilidades.ComprobarString(txtModNombre.getText());
                boolean r2=Utilidades.ComprobarString(txtModApellidos.getText());
                boolean r3=Utilidades.ComprobarString(txtModDireccion.getText());
                boolean r4=false;
                if(jdcCal.getDate()!=null){ r4=true;}
                
                if ((r1==true)&&(r2==true)&&(r3==true)&&(r4==true)){
                    java.util.Date ud = jdcCal.getDate();
                    long d = ud.getTime();
                    java.sql.Date fecha = new java.sql.Date(d);
                    int resp = JOptionPane.showConfirmDialog(this, "¿Quieres realizar los cambios?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
                        if(resp==0){
                            
                            m.modificarMusico(nombre, ape, dire, fecha, id);
                            String consulta="SELECT * FROM musico";
                            
                            ConexionBD conexion=new ConexionBD();
                            conexion.resultadoEnTabla(consulta);
                            txtModNombre.setVisible(false);
                            txtModApellidos.setVisible(false);
                            txtModDireccion.setVisible(false);
                            jdcCal.setVisible(false);
                            lNombreM.setVisible(false);
                            lApellidosM.setVisible(false);
                            lDireccionM.setVisible(false);
                            lFechaM.setVisible(false);
                        }
                }else if(r1==false){
                    JOptionPane.showMessageDialog(this, "Ingresa un nombre para el Músico!!!", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                    txtModNombre.requestFocus();
                }else if(r2==false){
                    JOptionPane.showMessageDialog(this, "Ingresa los apellidos para el Músico!!!", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                    txtModApellidos.requestFocus();
                }else if(r3==false){
                    JOptionPane.showMessageDialog(this, "Ingresa la dirección para el Músico!!!", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                    txtModDireccion.requestFocus();
                }else if(r4==false){
                    JOptionPane.showMessageDialog(this, "Ingresa una fecha para el Músico!!!", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }else{//pestaña 1 tabla instrumentos
            int indice=tablaInstrumentos.getSelectedRow();
            if(indice==-1){
                JOptionPane.showMessageDialog(this, "Selecciona primero el registro a modificar", "información", JOptionPane.INFORMATION_MESSAGE);
            }else{
                int idInst=(int) tablaInstrumentos.getValueAt(indice, 0);
                String nombre=txtModNombreI.getText();
                String desc=txtModDescripcionI.getText();
                int idmusico=cmbxModI.getItemAt(cmbxModI.getSelectedIndex()).getId();

                boolean r1=Utilidades.ComprobarString(txtModNombreI.getText());
                boolean r2=Utilidades.ComprobarString(txtModDescripcionI.getText());
                boolean r3=true;

                if ((r1==true)&&(r2==true)&&(r3==true)){
                    int resp = JOptionPane.showConfirmDialog(this, "¿Quieres realizar los cambios?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
                    if(resp==0){
                        i.modificarInstrumento(nombre, desc, idInst, idmusico);
                        String consulta="SELECT * FROM instrumento";
                        
                        ConexionBD conexion=new ConexionBD();
                        conexion.resultadoEnTabla(consulta);
                        txtModNombre.setVisible(false);
                        txtModApellidos.setVisible(false);
                        txtModDireccion.setVisible(false);
                        jdcCal.setVisible(false);
                        lNombreM.setVisible(false);
                        lApellidosM.setVisible(false);
                        lDireccionM.setVisible(false);
                        lFechaM.setVisible(false);
                    }
                }else if(r1==false){
                    JOptionPane.showMessageDialog(this, "Ingresa el nombre del Instrumento!!!", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                    txtModNombre.requestFocus();
                }else if(r2==false){
                    JOptionPane.showMessageDialog(this, "Ingresa la descripción del Instrumento!!!", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                    txtModApellidos.requestFocus();
                }else if(r3==false){
                    JOptionPane.showMessageDialog(this, "Selecciona al Músico que pertenece!!!", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                    txtModDireccion.requestFocus();
                }
            }
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        MyIcon icono = new MyIcon();
        icono.setRuta("/img/logout2.png");
                int resp = JOptionPane.showConfirmDialog(this, "¿Realmente quieres cerrar el programa?", "Cerrar", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE,icono);
                if(resp==0){
                    this.dispose();
                }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
        int indicePestana = panelPestanas.getSelectedIndex();
        String texto=txtBuscador.getText();
        if(indicePestana==0){
            Utilidades.filtrarPorApellido(texto);
        }else{
            Utilidades.filtrarPorNombre(texto);
        } 
    }//GEN-LAST:event_txtBuscadorKeyReleased

    private void txtBuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorMouseClicked
        txtBuscador.setText("");
        tablaMusicos.clearSelection();
        tablaInstrumentos.clearSelection();
        txtModNombre.setVisible(false);
        txtModApellidos.setVisible(false);
        txtModDireccion.setVisible(false);
        jdcCal.setVisible(false);
        lNombreM.setVisible(false);
        lApellidosM.setVisible(false);
        lDireccionM.setVisible(false);
        lFechaM.setVisible(false);
        
        txtModNombreI.setVisible(false);
        txtModDescripcionI.setVisible(false);
        cmbxModI.setVisible(false);
        lNombreI.setVisible(false);
        lDescripcionI.setVisible(false);
        lMusicoI.setVisible(false);  
    }//GEN-LAST:event_txtBuscadorMouseClicked

    private void tablaMusicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMusicosMouseClicked
        int indice=tablaMusicos.getSelectedRow();
        Date fecha=(Date)tablaInstrumentos.getValueAt(indice, 4);
        txtBuscador.setText("Buscar...");
        txtModNombre.setVisible(true);
        txtModApellidos.setVisible(true);
        txtModDireccion.setVisible(true);
        jdcCal.setVisible(true);
        lNombreM.setVisible(true);
        lApellidosM.setVisible(true);
        lDireccionM.setVisible(true);
        lFechaM.setVisible(true);
        txtModNombre.setText(tablaMusicos.getValueAt(indice,1).toString());
        txtModApellidos.setText(tablaMusicos.getValueAt(indice,2).toString());
        txtModDireccion.setText(tablaMusicos.getValueAt(indice,3).toString());
        jdcCal.setDate(fecha);
    }//GEN-LAST:event_tablaMusicosMouseClicked

    private void panelPestanasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPestanasMouseClicked
        int indice = panelPestanas.getSelectedIndex();
        if(indice==1){
            String consulta="SELECT idinstrumento AS 'Código', nombre AS Nombre, descripcion AS Descripción, idmusico AS 'Código Músico' FROM instrumento";
            
            ConexionBD conexion=new ConexionBD();
            conexion.resultadoEnTabla(consulta);
            txtModNombre.setVisible(false);
            txtModApellidos.setVisible(false);
            txtModDireccion.setVisible(false);
            jdcCal.setVisible(false);
            lNombreM.setVisible(false);
            lApellidosM.setVisible(false);
            lDireccionM.setVisible(false);
            lFechaM.setVisible(false);

            txtModNombreI.setVisible(false);
            txtModDescripcionI.setVisible(false);
            cmbxModI.setVisible(false);
            lNombreI.setVisible(false);
            lDescripcionI.setVisible(false);
            lMusicoI.setVisible(false);
        }else{
            String consulta="SELECT idmusico AS 'Nº Músico', nombre AS Nombre, apellidos AS Apellidos, direccion AS Dirección, fecha_nac AS 'Fecha de Nacimiento' FROM musico";
            
            ConexionBD conexion=new ConexionBD();
            conexion.resultadoEnTabla(consulta);
            txtModNombre.setVisible(false);
            txtModApellidos.setVisible(false);
            txtModDireccion.setVisible(false);
            jdcCal.setVisible(false);
            lNombreM.setVisible(false);
            lApellidosM.setVisible(false);
            lDireccionM.setVisible(false);
            lFechaM.setVisible(false);

            txtModNombreI.setVisible(false);
            txtModDescripcionI.setVisible(false);
            cmbxModI.setVisible(false);
            lNombreI.setVisible(false);
            lDescripcionI.setVisible(false);
            lMusicoI.setVisible(false);
        }
    }//GEN-LAST:event_panelPestanasMouseClicked


    private void tablaInstrumentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInstrumentosMouseClicked
        int indice=tablaInstrumentos.getSelectedRow();
        int idmusico=Integer.parseInt(tablaInstrumentos.getValueAt(indice, 3).toString());
        
        txtBuscador.setText("Buscar...");
        txtModNombre.setVisible(false);
        txtModApellidos.setVisible(false);
        txtModDireccion.setVisible(false);
        jdcCal.setVisible(false);
        lNombreM.setVisible(false);
        lApellidosM.setVisible(false);
        lDireccionM.setVisible(false);
        lFechaM.setVisible(false);
        
        txtModNombreI.setVisible(true);
        txtModDescripcionI.setVisible(true);
        cmbxModI.setVisible(true);
        lNombreI.setVisible(true);
        lDescripcionI.setVisible(true);
        lMusicoI.setVisible(true);

        //antes de hacer la consulta para rellenar el combobx lo vacio 
        cmbxModI.removeAllItems();
        /*  este bloque carga el combobox y recoge el indice del seleccionado en la tabla cuando coincide el id del musico de la tabla con 
        el id del musico  del objeto del combobox. asi luego puedo hacer que la seleccione*/
        try {
            Statement misentencia=miConexion.createStatement();
            ResultSet rs=misentencia.executeQuery("SELECT * FROM musico");
            int indiceCombo=0;
            //cmbxModI.addItem("Seleccione una opción...");
            while(rs.next()){
                Combo musico=new Combo(rs.getInt("idmusico"),rs.getString("nombre"),rs.getString("apellidos"));
                
                cmbxModI.addItem(musico);
                if(idmusico==musico.getId()){
                    indiceCombo=cmbxModI.getItemCount()-1;
                }
            }
            cmbxModI.setSelectedIndex(indiceCombo);
        } catch (SQLException ex) {
            System.out.println("ERROR Statement");
            
        }
        txtModNombreI.setText(tablaInstrumentos.getValueAt(indice,1).toString());
        txtModDescripcionI.setText(tablaInstrumentos.getValueAt(indice,2).toString());
    }//GEN-LAST:event_tablaInstrumentosMouseClicked

    private void btnMinimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimActionPerformed
      
    int xx,xy; 
    private void labelLogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoMousePressed
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_labelLogoMousePressed

    private void labelLogoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_labelLogoMouseDragged

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMinim;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<Combo> cmbxModI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private com.toedter.calendar.JDateChooser jdcCal;
    private javax.swing.JLabel lApellidosM;
    private javax.swing.JLabel lDescripcionI;
    private javax.swing.JLabel lDireccionM;
    private javax.swing.JLabel lFechaM;
    private javax.swing.JLabel lMusicoI;
    private javax.swing.JLabel lNombreI;
    private javax.swing.JLabel lNombreM;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelInstrumentos;
    private javax.swing.JPanel panelMusicos;
    private javax.swing.JTabbedPane panelPestanas;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaInstrumentos;
    public javax.swing.JTable tablaMusicos;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtModApellidos;
    private javax.swing.JTextField txtModDescripcionI;
    private javax.swing.JTextField txtModDireccion;
    private javax.swing.JTextField txtModNombre;
    private javax.swing.JTextField txtModNombreI;
    // End of variables declaration//GEN-END:variables
}
